-- MySQL Script generated by MySQL Workbench
-- Thu Apr  1 12:31:34 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library` DEFAULT CHARACTER SET utf8 ;
USE `library` ;

-- -----------------------------------------------------
-- Table `library`.`editor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`editor` (
  `ideditor` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`ideditor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`librarian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`librarian` (
  `idlibrarian` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idlibrarian`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`student` (
  `idstudent` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idstudent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`Adherent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`Adherent` (
  `idAdherent` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idAdherent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`¨professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`¨professor` (
  `id¨professor` INT NOT NULL,
  PRIMARY KEY (`id¨professor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`borrowbook`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`borrowbook` (
  `idborrowbook` INT NOT NULL,
  `` VARCHAR(45) NULL,
  `` VARCHAR(45) BINARY NULL,
  `student_idstudent` INT NOT NULL,
  `¨professor_id¨professor` INT NOT NULL,
  PRIMARY KEY (`idborrowbook`),
  INDEX `fk_borrowbook_student1_idx` (`student_idstudent` ASC) VISIBLE,
  INDEX `fk_borrowbook_¨professor1_idx` (`¨professor_id¨professor` ASC) VISIBLE,
  CONSTRAINT `fk_borrowbook_student1`
    FOREIGN KEY (`student_idstudent`)
    REFERENCES `library`.`student` (`idstudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_borrowbook_¨professor1`
    FOREIGN KEY (`¨professor_id¨professor`)
    REFERENCES `library`.`¨professor` (`id¨professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`CUSTUMER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`CUSTUMER` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `adress` VARCHAR(45) NULL,
  `nb_borrow` INT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `editor_ideditor` INT NOT NULL,
  `librarian_idlibrarian` INT NOT NULL,
  `student_idstudent` INT NOT NULL,
  `Adherent_idAdherent` INT NOT NULL,
  `¨professor_id¨professor` INT NOT NULL,
  `borrowbook_idborrowbook` INT NOT NULL,
  `borrowbook_idborrowbook1` INT NOT NULL,
  INDEX `fk_user_editor1_idx` (`editor_ideditor` ASC) VISIBLE,
  INDEX `fk_user_librarian1_idx` (`librarian_idlibrarian` ASC) VISIBLE,
  INDEX `fk_user_student1_idx` (`student_idstudent` ASC) VISIBLE,
  INDEX `fk_user_Adherent1_idx` (`Adherent_idAdherent` ASC) VISIBLE,
  INDEX `fk_user_¨professor1_idx` (`¨professor_id¨professor` ASC) VISIBLE,
  INDEX `fk_CUSTUMER_borrowbook1_idx` (`borrowbook_idborrowbook` ASC) VISIBLE,
  INDEX `fk_CUSTUMER_borrowbook2_idx` (`borrowbook_idborrowbook1` ASC) VISIBLE,
  CONSTRAINT `fk_user_editor1`
    FOREIGN KEY (`editor_ideditor`)
    REFERENCES `library`.`editor` (`ideditor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_librarian1`
    FOREIGN KEY (`librarian_idlibrarian`)
    REFERENCES `library`.`librarian` (`idlibrarian`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_student1`
    FOREIGN KEY (`student_idstudent`)
    REFERENCES `library`.`student` (`idstudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_Adherent1`
    FOREIGN KEY (`Adherent_idAdherent`)
    REFERENCES `library`.`Adherent` (`idAdherent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_¨professor1`
    FOREIGN KEY (`¨professor_id¨professor`)
    REFERENCES `library`.`¨professor` (`id¨professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CUSTUMER_borrowbook1`
    FOREIGN KEY (`borrowbook_idborrowbook`)
    REFERENCES `library`.`borrowbook` (`idborrowbook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CUSTUMER_borrowbook2`
    FOREIGN KEY (`borrowbook_idborrowbook1`)
    REFERENCES `library`.`borrowbook` (`idborrowbook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`category` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `categorycol` VARCHAR(45) NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`author` (
  `idauthor` INT NOT NULL,
  `lastname` VARCHAR(45) NULL,
  `img_author` TEXT(80) NULL,
  PRIMARY KEY (`idauthor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`books` (
  `idbooks` INT NOT NULL,
  `isbn` INT NULL,
  `title` VARCHAR(45) NULL,
  `language` VARCHAR(45) NULL,
  `years` VARCHAR(45) NULL,
  `datebuy` DATE NULL,
  `date_of_published` DATE NULL,
  `borrowbook_idborrowbook` INT NOT NULL,
  `author_idauthor` INT NOT NULL,
  PRIMARY KEY (`idbooks`),
  INDEX `fk_books_borrowbook1_idx` (`borrowbook_idborrowbook` ASC) VISIBLE,
  INDEX `fk_books_author1_idx` (`author_idauthor` ASC) VISIBLE,
  CONSTRAINT `fk_books_borrowbook1`
    FOREIGN KEY (`borrowbook_idborrowbook`)
    REFERENCES `library`.`borrowbook` (`idborrowbook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_books_author1`
    FOREIGN KEY (`author_idauthor`)
    REFERENCES `library`.`author` (`idauthor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`cathalogue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`cathalogue` (
  `idcathalogue` INT NOT NULL,
  `cathaloguecol` VARCHAR(45) NULL,
  PRIMARY KEY (`idcathalogue`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`editor_has_cathalogue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`editor_has_cathalogue` (
  `editor_ideditor` INT NOT NULL,
  `cathalogue_idcathalogue` INT NOT NULL,
  PRIMARY KEY (`editor_ideditor`, `cathalogue_idcathalogue`),
  INDEX `fk_editor_has_cathalogue_cathalogue1_idx` (`cathalogue_idcathalogue` ASC) VISIBLE,
  INDEX `fk_editor_has_cathalogue_editor1_idx` (`editor_ideditor` ASC) VISIBLE,
  CONSTRAINT `fk_editor_has_cathalogue_editor1`
    FOREIGN KEY (`editor_ideditor`)
    REFERENCES `library`.`editor` (`ideditor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_editor_has_cathalogue_cathalogue1`
    FOREIGN KEY (`cathalogue_idcathalogue`)
    REFERENCES `library`.`cathalogue` (`idcathalogue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
